# Generated by Django 5.0.2 on 2024-02-22 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0002_basicsite_delete_people"),
    ]

    operations = [
        migrations.CreateModel(
            name="Mesages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField()),
                ("email", models.EmailField(max_length=254)),
                ("message", models.TextField()),
                ("procesed", models.BooleanField(default=False)),
            ],
        ),
    ]
