# Generated by Django 5.0.2 on 2024-02-22 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0003_mesages"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Mesages",
            new_name="Messages",
        ),
    ]
