# Generated by Django 5.0.2 on 2024-02-22 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0008_lector"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Lector",
        ),
    ]
