# Generated by Django 5.0.3 on 2024-03-17 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0011_lector_order"),
    ]

    operations = [
        migrations.CreateModel(
            name="Region",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Název kraje")),
                ("slug", models.SlugField(unique=True)),
            ],
            options={
                "verbose_name": "kraj",
                "verbose_name_plural": "kraje",
            },
        ),
        migrations.CreateModel(
            name="CourseDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Datum kurzu")),
                (
                    "max_capacity",
                    models.PositiveIntegerField(verbose_name="Maximální kapacita"),
                ),
                (
                    "current_capacity",
                    models.PositiveIntegerField(verbose_name="Aktuální obsazenost"),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="webapp.course",
                        verbose_name="Kurz",
                    ),
                ),
                (
                    "lector",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="webapp.lector",
                        verbose_name="Lektor",
                    ),
                ),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="webapp.region",
                        verbose_name="Kraj",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kraj",
                "verbose_name_plural": "Kraje",
            },
        ),
        migrations.CreateModel(
            name="CourseParticipant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=255, verbose_name="Jméno")),
                (
                    "last_name",
                    models.CharField(max_length=255, verbose_name="Příjmení"),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="E-mail")),
                ("phone", models.CharField(max_length=255, verbose_name="Telefon")),
                (
                    "confirm",
                    models.BooleanField(default=False, verbose_name="Potvrzeno"),
                ),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="webapp.coursedetail",
                        verbose_name="Kraj",
                    ),
                ),
            ],
            options={
                "verbose_name": "Účastník kurzu",
                "verbose_name_plural": "Účastníci kurzu",
            },
        ),
    ]
