# Generated by Django 5.0.3 on 2024-03-17 16:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0017_remove_courseparticipant_region_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="courseparticipant",
            name="confirmation_code",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name="courseparticipant",
            name="confirmation_code_expires",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
