# Generated by Django 5.0.3 on 2024-03-17 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0018_courseparticipant_confirmation_code_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="coursedetail",
            options={
                "ordering": ["date"],
                "verbose_name": "Jednotlivý kurz",
                "verbose_name_plural": "Jednotlivé kurzy",
            },
        ),
    ]
