# Generated by Django 5.2.1 on 2025-07-29 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0022_course_program"),
    ]

    operations = [
        migrations.CreateModel(
            name="FinalCourseParticipant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=255, verbose_name="Jméno")),
                (
                    "last_name",
                    models.CharField(max_length=255, verbose_name="Příjmení"),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="E-mail")),
                ("phone", models.CharField(max_length=255, verbose_name="Telefon")),
            ],
            options={
                "verbose_name": "Účastník závěrečného kurzu",
                "verbose_name_plural": "Účastnici závěrečného kurzu",
                "ordering": ["last_name", "first_name"],
            },
        ),
        migrations.AlterField(
            model_name="courseparticipant",
            name="confirm",
            field=models.BooleanField(default=True, verbose_name="Potvrzeno"),
        ),
    ]
