# Generated by Django 5.2.1 on 2025-07-29 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0023_finalcourseparticipant_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="finalcourseparticipant",
            name="note",
            field=models.TextField(blank=True, null=True, verbose_name="Poznámka"),
        ),
    ]
