# Generated by Django 5.2.1 on 2025-08-04 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0024_finalcourseparticipant_note"),
    ]

    operations = [
        migrations.AddField(
            model_name="finalcourseparticipant",
            name="day_1",
            field=models.BooleanField(default=True, verbose_name="Termín 25.9."),
        ),
        migrations.AddField(
            model_name="finalcourseparticipant",
            name="day_2",
            field=models.BooleanField(default=True, verbose_name="Termín 26.9."),
        ),
    ]
