# Generated by Django 5.0.2 on 2024-02-22 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BasicSite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField()),
                ("title", models.CharField()),
                ("html", models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name="People",
        ),
    ]
