# Generated by Django 5.0.2 on 2024-02-22 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0005_message_delete_messages"),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("headline", models.CharField()),
                ("html", models.TextField()),
                ("image", models.ImageField(upload_to="courses_img")),
            ],
        ),
    ]
