# Generated by Django 5.0.2 on 2024-02-22 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0006_course"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="image_on_left",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="course",
            name="order",
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
