# Generated by Django 5.0.2 on 2024-02-22 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0009_delete_lector"),
    ]

    operations = [
        migrations.CreateModel(
            name="Lector",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Jméno")),
                ("about", models.TextField(verbose_name="Text o sobě")),
                (
                    "image",
                    models.ImageField(
                        upload_to="lektori_obrazky/", verbose_name="Obrázek"
                    ),
                ),
            ],
            options={
                "verbose_name": "Lektor",
                "verbose_name_plural": "Lektoři",
            },
        ),
    ]
