# Generated by Django 5.0.2 on 2024-02-22 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0010_lector"),
    ]

    operations = [
        migrations.AddField(
            model_name="lector",
            name="order",
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
