# Generated by Django 5.0.3 on 2024-03-17 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0014_alter_course_options_course_shortcut"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="shortcut",
            field=models.CharField(default=1, max_length=1),
            preserve_default=False,
        ),
    ]
