# Generated by Django 5.0.3 on 2024-03-17 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0015_alter_course_shortcut"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="shortcut",
            field=models.CharField(max_length=1, unique=True),
        ),
    ]
