# Generated by Django 5.0.3 on 2024-03-17 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0016_alter_course_shortcut"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="courseparticipant",
            name="region",
        ),
        migrations.AddField(
            model_name="courseparticipant",
            name="course_detail",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="webapp.coursedetail",
                verbose_name="Kurz",
            ),
            preserve_default=False,
        ),
    ]
