# Generated by Django 5.0.2 on 2024-03-26 10:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webapp", "0019_alter_coursedetail_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="courseparticipant",
            name="note",
            field=models.TextField(blank=True, null=True, verbose_name="Poznámka"),
        ),
    ]
