# Generated by Django 5.0.6 on 2024-05-28 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0020_courseparticipant_note"),
    ]

    operations = [
        migrations.AddField(
            model_name="coursedetail",
            name="spaces",
            field=models.CharField(blank=True, null=True, verbose_name="Prostory"),
        ),
    ]
