# Generated by Django 5.0.6 on 2024-05-28 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0021_coursedetail_spaces"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="program",
            field=models.FileField(default=1, upload_to="program/"),
            preserve_default=False,
        ),
    ]
